# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{captain_hook}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adam Pearson"]
  s.date = %q{2010-03-02}
  s.description = %q{Makes handling git hooks easy, with built-in notification to campfire}
  s.email = %q{ampearson@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "CHANGELOG.markdown",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "captain_hook.gemspec",
     "lib/captain_hook.rb",
     "lib/captain_hook/base.rb",
     "lib/captain_hook/dsl.rb",
     "lib/captain_hook/dsl/base.rb",
     "lib/captain_hook/dsl/handle_post_commit.rb",
     "lib/captain_hook/dsl/handle_post_receive.rb",
     "lib/captain_hook/events.rb",
     "lib/captain_hook/events/post_commit.rb",
     "lib/captain_hook/events/post_receive.rb",
     "spec/captain_hook/base_spec.rb",
     "spec/captain_hook/dsl/handle_post_commit_spec.rb",
     "spec/captain_hook/dsl/handle_post_receive_spec.rb",
     "spec/captain_hook/events/post_commit_spec.rb",
     "spec/captain_hook/events/post_receive_spec.rb",
     "spec/captain_hook_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/radamant/captain_hook}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A ruby manager for git hooks}
  s.test_files = [
    "spec/captain_hook/base_spec.rb",
     "spec/captain_hook/dsl/handle_post_commit_spec.rb",
     "spec/captain_hook/dsl/handle_post_receive_spec.rb",
     "spec/captain_hook/events/post_commit_spec.rb",
     "spec/captain_hook/events/post_receive_spec.rb",
     "spec/captain_hook_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<grit>, ["= 2.0.0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<grit>, ["= 2.0.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<grit>, ["= 2.0.0"])
  end
end

